@echo off
REM Auto-generated by tools/tests/_make_build_bat.py.
REM Do NOT hand-edit (will be regenerated). Edit _make_build_bat.py and rerun it.
REM Builds SimpleMarkdown.exe with -DENABLE_TEST_MODE=ON for the e2e harness.
REM
REM Usage:
REM   _build.bat              -- incremental build
REM   _build.bat --clean      -- delete CMakeCache.txt + CMakeFiles, then full build
set INCLUDE=
set LIB=
set LIBPATH=
set CPATH=
set C_INCLUDE_PATH=
set CPLUS_INCLUDE_PATH=
REM vcvars internals call vswhere.exe to locate Windows SDK; ensure Installer is on PATH
set "PATH=C:\Program Files (x86)\Microsoft Visual Studio\Installer;D:\Program Files (x86)\Microsoft Visual Studio\Installer;%PATH%"
call "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
if errorlevel 1 ( echo [_build] vcvars64 failed & exit /b 1 )
REM vcvars on this machine sometimes fails to inject Windows SDK include/lib paths
REM (vswhere edge case). Inject them manually so cl.exe can find stdlib.h / kernel32.lib.
set "WSDK_INC=C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0"
set "WSDK_LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0"
set "INCLUDE=%WSDK_INC%\ucrt;%WSDK_INC%\shared;%WSDK_INC%\um;%WSDK_INC%\winrt;%INCLUDE%"
set "LIB=%WSDK_LIB%\ucrt\x64;%WSDK_LIB%\um\x64;%LIB%"
set "PATH=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;%PATH%"
set "PATH=D:\Qt\Qt5.12.9\5.12.9\msvc2017_64\bin;%PATH%"
set "QT_PREFIX=D:\Qt\Qt5.12.9\5.12.9\msvc2017_64"
pushd D:\iflytek_projects\simple_markdown
echo [_build] cwd=%CD%
REM Optional clean: delete CMakeCache so cmake reconfigures from scratch
if "%~1"=="--clean" (
    echo [_build] cleaning build cache...
    if exist build\CMakeCache.txt del /q build\CMakeCache.txt
    if exist build\CMakeFiles rmdir /s /q build\CMakeFiles
)
cmake -S . -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release "-DCMAKE_PREFIX_PATH=%QT_PREFIX%" "-DENABLE_TEST_MODE=ON"
if errorlevel 1 ( echo [_build] cmake configure failed & popd & exit /b 1 )
cmake --build build
set RC=%errorlevel%
REM Deploy Qt runtime DLLs (windeployqt is idempotent; second run is a no-op)
if %RC%==0 if exist build\src\app\SimpleMarkdown.exe (
    if not exist build\src\app\platforms\qwindows.dll (
        echo [_build] deploying Qt runtime...
        "%QT_PREFIX%\bin\windeployqt.exe" --release --no-translations --no-system-d3d-compiler --no-opengl-sw --no-quick-import build\src\app\SimpleMarkdown.exe
    )
)
popd
exit /b %RC%
