"""生成 _build.bat（CRLF/ASCII）。run_all.py 在 build 阶段会用。

为什么用脚本生成而不是直接维护 .bat：
  cmd.exe 要求 CRLF 行尾、对中文注释敏感，git/编辑器可能在某些环境改坏；
  直接由 Python 在用 ASCII + CRLF 写出，规避所有编码/换行陷阱。

注意：本 .bat 当前包含本机绝对路径假设（VS2019 / Qt5.12.9 / Win10 SDK 19041）。
移植到其他开发机时，需要改 _build.bat 头部 4 个路径常量；或后续把这些常量
改为：vswhere 自动定位 / Qt5_DIR 环境变量 / 多 SDK 版本扫描。
"""
import sys
from pathlib import Path

# === 本机路径假设（改这里就能适配新机器）===
VS_VCVARS = r"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
QT_PREFIX = r"D:\Qt\Qt5.12.9\5.12.9\msvc2017_64"
WSDK_VER = "10.0.19041.0"  # Windows 10 SDK 版本
WSDK_INC_ROOT = r"C:\Program Files (x86)\Windows Kits\10\Include"
WSDK_LIB_ROOT = r"C:\Program Files (x86)\Windows Kits\10\Lib"
WSDK_BIN_ROOT = r"C:\Program Files (x86)\Windows Kits\10\bin"
VS_INSTALLER_C = r"C:\Program Files (x86)\Microsoft Visual Studio\Installer"
VS_INSTALLER_D = r"D:\Program Files (x86)\Microsoft Visual Studio\Installer"
PROJECT_ROOT = r"D:\iflytek_projects\simple_markdown"

lines = [
    r"@echo off",
    r"REM Auto-generated by tools/tests/_make_build_bat.py.",
    r"REM Do NOT hand-edit (will be regenerated). Edit _make_build_bat.py and rerun it.",
    r"REM Builds SimpleMarkdown.exe with -DENABLE_TEST_MODE=ON for the e2e harness.",
    r"REM",
    r"REM Usage:",
    r"REM   _build.bat              -- incremental build",
    r"REM   _build.bat --clean      -- delete CMakeCache.txt + CMakeFiles, then full build",

    r"set INCLUDE=",
    r"set LIB=",
    r"set LIBPATH=",
    r"set CPATH=",
    r"set C_INCLUDE_PATH=",
    r"set CPLUS_INCLUDE_PATH=",

    r"REM vcvars internals call vswhere.exe to locate Windows SDK; ensure Installer is on PATH",
    rf'set "PATH={VS_INSTALLER_C};{VS_INSTALLER_D};%PATH%"',
    rf'call "{VS_VCVARS}"',
    r"if errorlevel 1 ( echo [_build] vcvars64 failed & exit /b 1 )",

    r"REM vcvars on this machine sometimes fails to inject Windows SDK include/lib paths",
    r"REM (vswhere edge case). Inject them manually so cl.exe can find stdlib.h / kernel32.lib.",
    rf'set "WSDK_INC={WSDK_INC_ROOT}\{WSDK_VER}"',
    rf'set "WSDK_LIB={WSDK_LIB_ROOT}\{WSDK_VER}"',
    r'set "INCLUDE=%WSDK_INC%\ucrt;%WSDK_INC%\shared;%WSDK_INC%\um;%WSDK_INC%\winrt;%INCLUDE%"',
    r'set "LIB=%WSDK_LIB%\ucrt\x64;%WSDK_LIB%\um\x64;%LIB%"',
    rf'set "PATH={WSDK_BIN_ROOT}\{WSDK_VER}\x64;%PATH%"',

    rf'set "PATH={QT_PREFIX}\bin;%PATH%"',
    rf'set "QT_PREFIX={QT_PREFIX}"',

    rf"pushd {PROJECT_ROOT}",
    r'echo [_build] cwd=%CD%',

    r"REM Optional clean: delete CMakeCache so cmake reconfigures from scratch",
    r'if "%~1"=="--clean" (',
    r"    echo [_build] cleaning build cache...",
    r"    if exist build\CMakeCache.txt del /q build\CMakeCache.txt",
    r"    if exist build\CMakeFiles rmdir /s /q build\CMakeFiles",
    r")",

    r'cmake -S . -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release "-DCMAKE_PREFIX_PATH=%QT_PREFIX%" "-DENABLE_TEST_MODE=ON"',
    r"if errorlevel 1 ( echo [_build] cmake configure failed & popd & exit /b 1 )",

    r"cmake --build build",
    r"set RC=%errorlevel%",

    r"REM Deploy Qt runtime DLLs (windeployqt is idempotent; second run is a no-op)",
    r"if %RC%==0 if exist build\src\app\SimpleMarkdown.exe (",
    r"    if not exist build\src\app\platforms\qwindows.dll (",
    r"        echo [_build] deploying Qt runtime...",
    r'        "%QT_PREFIX%\bin\windeployqt.exe" --release --no-translations --no-system-d3d-compiler --no-opengl-sw --no-quick-import build\src\app\SimpleMarkdown.exe',
    r"    )",
    r")",

    r"popd",
    r"exit /b %RC%",
]

out = Path(__file__).parent / "_build.bat"
data = ("\r\n".join(lines) + "\r\n").encode("ascii")
out.write_bytes(data)
print(f"wrote {out} ({len(data)} bytes, CRLF)")
